;;; tabularium-modeline.el --- Modeline integration for Tabularium -*- lexical-binding: t; -*-

;; Author: Paul H. McClelland
;; SPDX-License-Identifier: GPL-3.0-or-later
;; Copyright (C) 2026 Paul H. McClelland

;; Version: 0.4.3
;; Package-Requires: ((emacs "29.1"))
;; Keywords: data, faces
;; URL: https://codeberg.org/phmcc/tabularium

;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Modeline integration for Tabularium, supporting multiple modeline packages:
;;
;;   - Standard Emacs mode line
;;   - doom-modeline
;;   - powerline
;;   - spaceline
;;   - mood-line
;;   - simple-modeline
;;   - telephone-line (manual setup required, see below)
;;
;; ============================================================================
;; STANDARD MODE LINE SETUP
;; ============================================================================
;;
;;   (require 'tabularium-modeline)
;;   (tabularium-modeline-mode 1)
;;
;; ============================================================================
;; DOOM-MODELINE SETUP
;; ============================================================================
;;
;;   (require 'tabularium-modeline)
;;   (tabularium-modeline-setup 'doom-modeline)
;;   ;; Then add 'tabularium to the doom-modeline format
;;
;; ============================================================================
;; TELEPHONE-LINE SETUP (manual)
;; ============================================================================
;;
;; Due to load-order constraints, define the segment inline in the main config:
;;
;;   (use-package telephone-line
;;     :config
;;     (telephone-line-defsegment telephone-line-tabularium-segment ()
;;       (when (and (boundp 'tabularium--current-schema-name)
;;                  tabularium--current-schema-name)
;;         (let ((backend-name (when (and (boundp 'tabularium--db)
;;                                        tabularium--db)
;;                               (ignore-errors
;;                                 (tabularium-db-backend-name tabularium--db)))))
;;           (propertize (format "[%s:%s]"
;;                               (or backend-name "Tab")
;;                               tabularium--current-schema-name)
;;                       'face 'font-lock-constant-face))))
;;
;;     (setq telephone-line-rhs
;;           '((accent . (telephone-line-tabularium-segment
;;                        telephone-line-vc-segment))
;;             ...))
;;     (telephone-line-mode 1))
;;
;; ============================================================================
;; CUSTOMIZATION
;; ============================================================================
;;
;;   (setq tabularium-modeline-use-icon t)        ; Use icon (default: nil)
;;   (setq tabularium-modeline-icon "T")          ; Icon string to use
;;   (setq tabularium-modeline-show-schema t)     ; Show table name (default: t)
;;   (setq tabularium-modeline-format 'full)      ; 'full, 'minimal, 'icon-only
;;   (setq tabularium-modeline-contextual nil)    ; Only show in tabularium buffers

;;; Code:

(require 'tabularium)

;; Forward declarations for optional modeline packages
(defvar awesome-tray-module-alist)
(defvar tabularium-modeline-powerline-segment)
;; Segment-name variables generated by doom-modeline/spaceline macros at runtime
(declare-function doom-modeline-def-segment "doom-modeline-core" (name &rest body))
(declare-function doom-modeline-icon "doom-modeline-core" (icon-set icon-name &rest args))
(declare-function doom-modeline-spc "doom-modeline-core" nil)
(declare-function defpowerline "powerline" (name &rest body))
(declare-function spaceline-define-segment "spaceline" (name &rest args))

;;; * 1 Customization

(defgroup tabularium-modeline nil
  "Modeline integration for Tabularium."
  :group 'tabularium
  :prefix "tabularium-modeline-")

(defcustom tabularium-mode-line-format
  '(:eval (tabularium-modeline-string-with-props))
  "Mode line construct for displaying current database.
Set to nil to disable.  This is used by `tabularium-modeline-mode'."
  :type 'sexp
  :group 'tabularium-modeline)

(defcustom tabularium-modeline-use-icon nil
  "Whether to use an icon in the modeline segment.
When non-nil, displays an icon (from `tabularium-modeline-icon' or a
Nerd Font glyph if available).  When nil, displays the backend name."
  :type 'boolean
  :group 'tabularium-modeline)

(defcustom tabularium-modeline-icon nil
  "Icon string for the modeline when `tabularium-modeline-use-icon' is t.
Set to any string, e.g. a Nerd Font glyph or a short label like
\"T\" or \"DB\"."
  :type '(choice (string :tag "Icon string")
                 (const :tag "None" nil))
  :group 'tabularium-modeline)

(defcustom tabularium-modeline-nerd-font-icon nil
  "Nerd Font icon to use when nerd-icons is available.
For example, the nf-fa-database glyph.  Set to nil to use
`tabularium-modeline-icon' instead."
  :type '(choice string (const nil))
  :group 'tabularium-modeline)

(defcustom tabularium-modeline-show-schema t
  "Whether to show the schema/table name in addition to database name.
When non-nil and using icons: [<icon> DatabaseName:data]
When nil and using icons: [<icon> DatabaseName]"
  :type 'boolean
  :group 'tabularium-modeline)

(defcustom tabularium-modeline-format 'full
  "Format for the modeline segment.
- `full': Show icon/prefix, database name, and optionally schema
- `minimal': Show only database name
- `icon-only': Show only icon when database is open"
  :type '(choice (const :tag "Full: [Backend | DB:schema]" full)
                 (const :tag "Minimal: [DB]" minimal)
                 (const :tag "Icon only" icon-only))
  :group 'tabularium-modeline)

(defcustom tabularium-modeline-contextual nil
  "When non-nil, only show segment in Tabularium-related buffers."
  :type 'boolean
  :group 'tabularium-modeline)

;;; * 2 Faces

(defface tabularium-modeline-database
  '((t (:inherit font-lock-constant-face :weight bold)))
  "Face for database name in modeline."
  :group 'tabularium-modeline)

(defface tabularium-modeline-schema
  '((t (:inherit font-lock-type-face)))
  "Face for schema/table name in modeline."
  :group 'tabularium-modeline)

(defface tabularium-modeline-icon
  '((t (:inherit font-lock-keyword-face)))
  "Face for icon in modeline."
  :group 'tabularium-modeline)

(defface tabularium-modeline-bracket
  '((t (:inherit shadow)))
  "Face for brackets in modeline."
  :group 'tabularium-modeline)

;;; * 3 Core Functions

(defun tabularium-modeline--backend-name ()
  "Get the current backend name (e.g., SQLite, PostgreSQL)."
  (when (and (boundp 'tabularium--db) tabularium--db)
    (ignore-errors (tabularium-db-backend-name tabularium--db))))

(defun tabularium-modeline--icon ()
  "Return the icon string for the modeline, or nil if none configured.
Prefers `tabularium-modeline-nerd-font-icon' when a Nerd Font package is
loaded, then falls back to `tabularium-modeline-icon'."
  (cond
   ;; Use nerd-font icon if available and configured
   ((and tabularium-modeline-nerd-font-icon
         (or (featurep 'nerd-icons)
             (featurep 'all-the-icons-nerd-fonts)))
    (propertize tabularium-modeline-nerd-font-icon
                'face 'tabularium-modeline-icon))
   ;; Use user-configured icon string
   (tabularium-modeline-icon
    (propertize tabularium-modeline-icon
                'face 'tabularium-modeline-icon))))

(defun tabularium-modeline--in-context-p ()
  "Return non-nil if we should show the segment based on context."
  (or (not tabularium-modeline-contextual)
      (derived-mode-p 'tabularium-view-mode)
      (derived-mode-p 'tabularium-entry-mode)))

(defun tabularium-modeline--active-p ()
  "Return non-nil if Tabularium has an active database."
  (and (boundp 'tabularium--current-schema-name)
       tabularium--current-schema-name
       (tabularium-modeline--in-context-p)))

(defun tabularium-modeline-string ()
  "Return the modeline string for Tabularium.
Returns nil if no database is active."
  (when (tabularium-modeline--active-p)
    (let ((db-name tabularium--current-schema-name)
          (backend (tabularium-modeline--backend-name)))
      (pcase tabularium-modeline-format
        ('icon-only
         (if-let ((icon (tabularium-modeline--icon)))
             (propertize icon 'help-echo (format "Tabularium: %s" db-name))
           ;; No icon configured; fall back to short database name
           (propertize db-name 'face 'tabularium-modeline-database
                       'help-echo (format "Tabularium: %s" db-name))))
        ('minimal
         (concat
          (propertize "[" 'face 'tabularium-modeline-bracket)
          (propertize db-name 'face 'tabularium-modeline-database)
          (propertize "]" 'face 'tabularium-modeline-bracket)))
        ('full
         ;; Format: [Protocol | Database] - shows backend type and database name
         (let ((icon (and tabularium-modeline-use-icon
                         (tabularium-modeline--icon))))
           (concat
            (propertize "[" 'face 'tabularium-modeline-bracket)
            (if icon
                ;; Icon mode: [<Icon> | Database]
                (concat icon
                        (propertize " | " 'face 'tabularium-modeline-bracket))
              ;; Text mode: [SQLite | Database]
              (concat (propertize (or backend "Tab") 'face 'tabularium-modeline-icon)
                      (propertize " | " 'face 'tabularium-modeline-bracket)))
            (propertize db-name 'face 'tabularium-modeline-database)
            (propertize "]" 'face 'tabularium-modeline-bracket))))
        (_ "")))))

(defun tabularium-modeline-string-with-props ()
  "Return modeline string with mouse properties."
  (when-let ((str (tabularium-modeline-string)))
    (propertize str
                'help-echo (format "Tabularium: %s\nmouse-1: Open menu"
                                   tabularium--current-schema-name)
                'mouse-face 'mode-line-highlight
                'local-map (let ((map (make-sparse-keymap)))
                             (define-key map [mode-line mouse-1]
                                         (lambda ()
                                           (interactive)
                                           (if (fboundp 'tabularium-hydra/body)
                                               (tabularium-hydra/body)
                                             (call-interactively #'tabularium-view))))
                             map))))

;;; * 4 Mode Line Formats

;;; ** 4.1 Standard Mode Line

(defvar tabularium-modeline--standard-construct
  '(:eval (tabularium-modeline-string-with-props))
  "Mode line construct for standard Emacs mode line.")

(defun tabularium-modeline--standard-enable ()
  "Enable Tabularium segment in standard mode line."
  (unless (member tabularium-modeline--standard-construct
                  global-mode-string)
    (push tabularium-modeline--standard-construct global-mode-string)))

(defun tabularium-modeline--standard-disable ()
  "Disable Tabularium segment in standard mode line."
  (setq global-mode-string
        (delete tabularium-modeline--standard-construct global-mode-string)))

;;; ** 4.2 Telephone Line

;; NOTE: telephone-line requires segments to be defined BEFORE the layout is set,
;; which creates complex load-order issues with use-package. For telephone-line,
;; we recommend defining the segment inline in your telephone-line config:
;;
;;   (use-package telephone-line
;;     :config
;;     (telephone-line-defsegment telephone-line-tabularium-segment ()
;;       (when (and (boundp 'tabularium--current-schema-name)
;;                  tabularium--current-schema-name)
;;         (propertize (format " [DB:%s] " tabularium--current-schema-name)
;;                     'face 'font-lock-constant-face)))
;;
;;     (setq telephone-line-rhs
;;           '((accent . (telephone-line-tabularium-segment ...))
;;             ...))
;;     (telephone-line-mode 1))

(defun tabularium-modeline--telephone-line-setup ()
  "Note: telephone-line setup is not automated due to load-order constraints.
See the commentary in tabularium-modeline.el for inline setup instructions."
  (message "Tabularium: For telephone-line, define the segment inline in your config. See tabularium-modeline.el for example."))

;;; ** 4.3 Doom Modeline

(defun tabularium-modeline--doom-setup ()
  "Set up Tabularium segment for doom-modeline."
  (with-eval-after-load 'doom-modeline
    ;; doom-modeline-def-segment generates a variable named `tabularium'
    (with-no-warnings
      (doom-modeline-def-segment tabularium
                                 "Display current Tabularium database."
                                 (when (tabularium-modeline--active-p)
                                   (let ((backend (tabularium-modeline--backend-name)))
                                     (concat
                                      (doom-modeline-spc)
                                      (if tabularium-modeline-use-icon
                                          ;; Icon mode: try doom icon, then user icon, then text
                                          (let ((icon (or (doom-modeline-icon 'faicon "database" nil nil
                                                                              :face 'tabularium-modeline-icon)
                                                          (tabularium-modeline--icon))))
                                            (if icon
                                                (concat icon " |")
                                              (propertize (format "%s |" (or backend "Tab"))
                                                          'face 'tabularium-modeline-icon)))
                                        ;; Text mode: "SQLite |"
                                        (propertize (format "%s |" (or backend "Tab"))
                                                    'face 'tabularium-modeline-icon))
                                      (doom-modeline-spc)
                                      (propertize tabularium--current-schema-name
                                                  'face 'tabularium-modeline-database
                                                  'help-echo (format "Tabularium: %s" tabularium--current-schema-name))
                                      (when (and tabularium-modeline-show-schema
                                                 (boundp 'tabularium-table-name)
                                                 tabularium-table-name)
                                        (concat
                                         (propertize ":" 'face 'tabularium-modeline-bracket)
                                         (propertize tabularium-table-name 'face 'tabularium-modeline-schema)))
                                      (doom-modeline-spc))))))

    (message "Tabularium: doom-modeline segment defined. Add `tabularium' to your doom-modeline format.")))

;;; ** 4.4 Powerline / Spaceline

(defun tabularium-modeline--powerline-setup ()
  "Set up Tabularium segment for powerline/spaceline."
  (with-eval-after-load 'powerline
    (defpowerline tabularium-modeline-powerline-segment
                  (tabularium-modeline-string))
    (message "Tabularium: powerline segment defined.")))

(defun tabularium-modeline--spaceline-setup ()
  "Set up Tabularium segment for spaceline."
  (with-eval-after-load 'spaceline
    ;; spaceline-define-segment generates a variable named `tabularium'
    (with-no-warnings
      (spaceline-define-segment tabularium
                                "Display current Tabularium database."
                                (tabularium-modeline-string)
                                :when (tabularium-modeline--active-p)))
    (message "Tabularium: spaceline segment defined. Add `tabularium' to your spaceline.")))

;;; ** 4.5 Mood Line

(defun tabularium-modeline--mood-line-setup ()
  "Set up Tabularium segment for mood-line."
  (with-eval-after-load 'mood-line
    (defun mood-line-segment-tabularium ()
      "Return Tabularium segment for mood-line."
      (when (tabularium-modeline--active-p)
        (concat " " (tabularium-modeline-string) " ")))
    (message "Tabularium: mood-line segment defined. Add `mood-line-segment-tabularium' to your format.")))

;;; ** 4.6 Simple Modeline

(defun tabularium-modeline--simple-modeline-setup ()
  "Set up Tabularium segment for simple-modeline."
  (with-eval-after-load 'simple-modeline
    (defun simple-modeline-segment-tabularium ()
      "Return Tabularium segment for simple-modeline."
      (tabularium-modeline-string-with-props))
    (message "Tabularium: simple-modeline segment defined.")))

;;; ** 4.7 Awesome Tray

(defun tabularium-modeline--awesome-tray-setup ()
  "Set up Tabularium module for awesome-tray."
  (with-eval-after-load 'awesome-tray
    (defun awesome-tray-module-tabularium-info ()
      "Return Tabularium info for awesome-tray."
      (or (tabularium-modeline-string) ""))
    (add-to-list 'awesome-tray-module-alist
                 '("tabularium" . (awesome-tray-module-tabularium-info
                                   tabularium-modeline-database)))
    (message "Tabularium: awesome-tray module defined. Add \"tabularium\" to `awesome-tray-active-modules'.")))

;;; * 5 Auto-Detection and Minor Mode

(defun tabularium-modeline-setup (&optional modeline)
  "Set up Tabularium segment for MODELINE package.
If MODELINE is nil, attempt to detect and set up all available modelines.
MODELINE can be one of:
  `standard'       - Standard Emacs mode line
  `telephone-line' - telephone-line package
  `doom-modeline'  - doom-modeline package
  `powerline'      - powerline package
  `spaceline'      - spaceline package
  `mood-line'      - mood-line package
  `simple-modeline'- simple-modeline package
  `awesome-tray'   - awesome-tray package"
  (interactive
   (list (intern (completing-read "Modeline package: "
                                  '("standard" "telephone-line" "doom-modeline"
                                    "powerline" "spaceline" "mood-line"
                                    "simple-modeline" "awesome-tray" "all")
                                  nil t))))
  (pcase modeline
    ('standard (tabularium-modeline--standard-enable))
    ('telephone-line (tabularium-modeline--telephone-line-setup))
    ('doom-modeline (tabularium-modeline--doom-setup))
    ('powerline (tabularium-modeline--powerline-setup))
    ('spaceline (tabularium-modeline--spaceline-setup))
    ('mood-line (tabularium-modeline--mood-line-setup))
    ('simple-modeline (tabularium-modeline--simple-modeline-setup))
    ('awesome-tray (tabularium-modeline--awesome-tray-setup))
    ((or 'all 'nil)
     ;; Standard is always available
     (tabularium-modeline--standard-enable)
     ;; Set up others if their packages are available
     (when (featurep 'telephone-line)
       (tabularium-modeline--telephone-line-setup))
     (when (featurep 'doom-modeline)
       (tabularium-modeline--doom-setup))
     (when (featurep 'powerline)
       (tabularium-modeline--powerline-setup))
     (when (featurep 'spaceline)
       (tabularium-modeline--spaceline-setup))
     (when (featurep 'mood-line)
       (tabularium-modeline--mood-line-setup))
     (when (featurep 'simple-modeline)
       (tabularium-modeline--simple-modeline-setup))
     (when (featurep 'awesome-tray)
       (tabularium-modeline--awesome-tray-setup)))))

;;;###autoload
(define-minor-mode tabularium-modeline-mode
  "Toggle Tabularium modeline indicator.
When enabled, shows the current database in the mode line."
  :global t
  :group 'tabularium-modeline
  (if tabularium-modeline-mode
      (tabularium-modeline-setup 'all)
    (tabularium-modeline--standard-disable)))

;;; * 6 Provide

(provide 'tabularium-modeline)

;;; tabularium-modeline.el ends here
